name: BuildOnPush

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build-push:
    if: github.repository != 'intel/trustauthority-client-for-c'
    runs-on: [ self-hosted ]
    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: ${{ secrets.NO_PROXY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          ref: main
          path: client-c
          fetch-depth: 0

      - name: Build Client C docker images
        run: |
          make all
          make tar-images
          
      - name: Upload Client Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-c-${{ github.run_number }}
          path: client-c/trust_authority.*.tar.gz
